# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      matrix:
        python-version: [3.7]

    - name: TEST GUSTAVO 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        python servidor.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Automatización descargas"
        branch: main

        repository: .

        commit_user_name: Actions Bot
        commit_user_email: Gholley42@gmail.com
        commit_author: DataIntelligence BOT <Gholley42@gmail.com>
        push_options: '--force'
